export enum FindFreightStrategy {
  ALL = 'ALL',
  FREIGHT_TYPE = 'FREIGHT_TYPE',
  ORIGIN = 'ORIGIN',
  DESTINATION = 'DESTINATION',
  TRANSIT_TIME = 'TRANSIT_TIME',
  VALID_FROM = 'VALID_FROM',
  VALID_UNTIL = 'VALID_UNTIL',
  ADDITIONAL_FEE = 'ADDITIONAL_FEE',
  ADDITIONAL_FEE_BREAKDOWN = 'ADDITIONAL_FEE_BREAKDOWN',
  SCHEDULE = 'SCHEDULE',
  PROVIDER_ID = 'PROVIDER_ID',
}