services:
  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  exim-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    expose:
      - "3000"
    depends_on:
      - exim-db
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=exim-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.exim-api.rule=Host(`exim-api.localhost`)"

  exim-db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.exim-db.rule=Host(`exim-db.localhost`)"


volumes:
  postgres-data:
