export enum FindQuotationStrategy {
  ALL = 'ALL',
  DELIVERY_DATE = 'DELIVERY_DATE',
  EXPIRED_DATE = 'EXPIRED_DATE',
  PICKUP_DATE = 'PICKUP_DATE',
  QUOTATION_DATE = ' QUOTATION_DATE',
  STATUS = 'STATUS',
  TOTAL_PRICE = 'TOTAL_PRICE',
  EMPLOYEE_ID = 'EMPLOYEE_ID',
  CUSTOMER_ID = 'CUSTOMER_ID',
}
