export enum FindFreightStrategy {
  ALL = 'ALL',
  FREIGHT_TYPE = 'FREIGHT_TYPE',
  ORIGIN = 'ORIGIN',
  DESTINATION = 'DESTINATION',
  TRANSIT = 'TRANSIT',
  TRANSIT_TIME = 'TRANSIT_TIME',
  VALID_FROM = 'VALID_FROM',
  VALID_UNTIL = 'VALID_UNTIL',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
}