export enum FindContactRepsStrategy {
  ALL = 'ALL',
  NAME = 'NAME',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  CONTACT_REP_ID = 'CONTACT_REP_ID',
  BRANCH_LOCATION = 'BRANCH_LOCATION',
  PROVIDER_ID = 'PROVIDER_ID'
}