export enum FindQuoteReqDetailStrategy {
    ALL = 'ALL',
    ORIGIN = 'ORIGIN',
    DESTINATION = 'DESTINATION',
    SHIPMENTREADYDATE = 'SHIPMENTREADYDATE',
    SHIPMENTDEADLINE = 'SHIPMENTDEADLINE',
    CARGOINSURANCE = 'CARGOINSURANCE',
    QUOTEREQID = 'QUOTEREQID'
}
