export enum FindAirFreightStrategy {
  PRICE_0K = 'PRICE_0K',
  PRICE_45K = 'PRICE_45K',
  PRICE_100K = 'PRICE_100K',
  PRICE_300K = 'PRICE_300K',
  PRICE_500K = 'PRICE_500K',
  ALL = 'ALL',
  FREIGHT_ID = 'FREIGHT_ID',
  AIR_FREIGHT_ID = 'AIR_FREIGHT_ID',
}
