export enum DocumentType {
  CUSTOM_IMPORT = 'CUSTOM_IMPORT',
  CUSTOM_EXPORT = 'CUSTOM_EXPORT',
  LANDING_BILL = 'LANDING_BILL',
  AIRWAY_BILL = 'AIRWAY_BILL',
  PACKING_LIST = 'PACKING_LIST',
  COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE',
  ORIGIN_CERTIFICATE = 'ORIGIN_CERTIFICATE',
  EXIM_LISENCE = 'EXIM_LISENCE',
  SALES_CONTRACT = 'SALES_CONTRACT',
  FORWARDER_PROVIDER_CONTRACT = 'FORWARDER_PROVIDER_CONTRACT',
  CUSTOMER_FORWARDER_CONTRACT = 'CUSTOMER_FORWARDER_CONTRACT',
}
