export enum RoleEnum {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  SALES = 'SALES',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  HUMAN_RESOURCES = 'HUMAN_RESOURCES',
  DOCUMENTATION = 'DOCUMENTATION',
  CLIENT = 'CLIENT',
}

